<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>ValheimCustomItemRegistry</RootNamespace>
    <AssemblyName>CustomItemRegistry</AssemblyName>
    <Version>0.6.0</Version>
    <Authors>BreakoutMods</Authors>
    <Company>BreakoutMods</Company>
    <RepositoryUrl>https://github.com/BreakoutMods/CIR-CustomItemRegistry</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCoreDir)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCoreDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Jotunn">
      <HintPath>$(JotunnDir)\Jotunn.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>$(ValheimManagedDir)\assembly_valheim.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>$(ValheimManagedDir)\assembly_utils.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>$(ValheimManagedDir)\netstandard.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ValheimManagedDir)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ValheimManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(ValheimManagedDir)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(ValheimManagedDir)\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyToBepInEx" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug'">
    <MakeDir Directories="$(BepInExDir)\plugins\CustomItemRegistry" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BepInExDir)\plugins\CustomItemRegistry" />
  </Target>
</Project>
